export const Theme = {
    borders: {
        RADIUS: 5,
    },
    colors: {
        BRAND: '#00205B',
        BRAND_CONTRAST: '#fff',
        SUBHEADER_BG: '#E9F1FF',
        PRIMARY_TEXT: '#00205B',
        SECONDARY_TEXT: '#616265',
        TERTIARY_TEXT: '#848891',
        PRIMARY: '#00205B',
        PRIMARY_VARIANT: '#00A0DF',
        PRIMARY_CONTRAST: '#616265',
        PRIMARY_DARK: '#FF9900',
        SECONDARY: '#004E9F',
        SECONDARY_VARIANT: '#AB9344',
        SECONDARY_CONTRAST: '#FFF8DE',
        TERTIARY: '#009900',
        TERTIARY_VARIANT: '#E9EDF0',
        TERTIARY_CONTRAST: '#CCD6DF',
        TERTIARY_DARK: '#9AA7B3',
        BACKGROUND: '#f8f8f8',
        BACKGROUND_BUTTON: '#fff',
        BACKGROUND_PAPER: '#f2f2f2',
        DISABLED_BACKGROUND: '#CCD6DF',
        DISABLED: '#E9EDF0',
        DIVIDER: '#CCD6DF',
        BORDER: '#CCD6DF',
        BORDER_LIGHT: '#74818D',
        BORDER_DARK: '#00205B',
        ERROR: '#CC0000',
        ERROR_LIGHT: '#E20033',
        WARNING: '#8E6E06',
        TOOLTIP_BACKGROUND: '#CCD6DF',
        TOOLTIP_TEXT: '#0A2C6E',
        PRIMARY_BUTTON_BG: '#00205B',
        BUTTON_HOVER: '#004E9F',
        PRIMARY_BUTTON_INACTIVE: '#ccc',
        SECONDARY_BUTTON_BG: '#FFFFFF',
        SECONDARY_BUTTON_HOVER: '#E7EEFB',
        SECONDARY_BUTTON_INACTIVE: '#E9EDF0',
        TABLE_BG: '#F1F3DB',
        TABLE_ROW_HOVER: '#FFF8DE',
        CALENDER_BG: '#E9F1FF',
        INPUT_FIELD_FOCUS_BG: '#FFCC00',
        popup_BG: '#DCE8EE',
    },
    fonts: {
        FONT: ['raleway', 'sans-serif'],
    },
    fontVarients: {
        RalewayBold: 'RalewayBold',
        RalewayLight: 'RalewayLight',
        RalewayMedium: 'RalewayMedium',
        RalewaySemiBold: 'RalewaySemiBold',
        RalewaySemiBoldItalic: 'RalewaySemiBoldItalic',
        RalewayRegular: 'RalewayRegular',
        RalewayLightItalic: 'RalewayLightItalic',
        RalewayMediumItalic: 'RalewayMediumItalic',
    },
    layout: {
        PAGE_WIDTH: 1550,
    },
};
